In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv("./clinic.csv")

In [10]:
a = data.loc[data.BMI >2]

In [13]:
a.index = range(len(a))

In [14]:
a

,PID,Sex,Age,BMI,Comorbidity,PCEA,GT,pT,pN,Stage,...,Differentiation,Neural_Invasion,Vascular_Invasion,Lymphatic_Invasion,K-ras,Adjuvant_Tx,Censored_flag,recurrence,days_to_followup,Event_flag
0,1323487,1,2,3,2,1.90,2,3,0,2,...,2,1,0,0,1,1,1,0,1626,0
1,13607,2,5,3,2,5.32,3,3,0,2,...,1,0,0,0,1,0,1,0,4572,0
2,122761,2,5,3,3,7.23,2,3,0,2,...,2,0,0,1,0,1,1,0,2211,0
3,1121671,1,3,4,1,15.47,3,3,0,2,...,2,1,0,0,1,1,1,1,2211,0
4,1117483,2,3,3,2,3.01,2,3,0,2,...,2,0,0,0,2,0,1,0,30,0
5,1115619,1,4,3,2,2.15,1,3,0,2,...,2,0,0,0,2,0,1,0,2187,0
6,116968,2,5,3,2,1.82,3,4,0,2,...,2,1,1,1,2,1,1,0,1853,0
7,10643,1,3,3,0,5.50,5,4,0,2,...,2,1,0,1,2,1,1,0,368,0
8,1215519,1,4,3,1,1.39,1,2,1,3,...,2,0,0,0,1,1,1,0,1788,0
9,1328390,2,3,3,0,1.50,2,3,1,3,...,2,0,0,0,0,1,1,0,1560,0
10,1213841,2,3,3,2,1.02,3,3,2,3,...,2,0,0,0,0,1,1,0,3182,0
11,1111044,2,2,3,1,18.11,2,3,1,3,...,2,0,0,1,2,1,1,0,1741,0
12,1110034,1,4,3,2,15.49,2,3,1,3,...,2,1,0,0,2,1,1,0,2128,0
13,1011770,2,3,3,0,4.19,3,3,1,3,...,2,0,0,1,2,1,1,0,2062,0
14,94912,2,4,3,1,2.74,2,3,2,3,...,2,0,0,0,2,1,1,0,3122,0
15,1115952,1,1,3,0,8.53,2,3,2,3,...,-1,1,0,1,2,1,1,1,834,0
16,1016181,1,2,3,2,2.71,2,3,1,3,...,2,1,0,1,2,1,1,1,2597,0
17,1312503,2,3,3,0,2.30,3,3,0,2,...,2,0,0,0,0,1,1,0,1112,0
18,113703,2,3,3,2,1.40,3,3,0,2,...,2,0,0,0,2,1,1,0,1122,0
19,102267,1,2,3,0,6.06,3,3,0,2,...,2,1,0,0,2,1,1,1,2507,0
20,93624,2,5,3,1,4.19,1,2,1,3,...,2,1,0,1,2,0,1,0,3290,0
21,138669,2,5,3,2,31.85,2,4,1,3,...,2,1,0,1,0,0,1,2,1806,0
22,1211079,1,1,3,0,0.72,3,3,2,3,...,2,0,0,0,1,1,1,0,4129,0

In [197]:
# PID 생성
for i, row in data.iterrows():
    a = row[0].split("-")
    if "20" in a[1]:
        data.iloc[i,0] = a[1][-2:] + a[2]
    else : 
        data.iloc[i,0] = a[1]+a[2]

In [199]:
# AGE 카테고리
i=0
j=20
while i < 8:
    a = data.loc[data.Age.isin(range(j,j+10))].index.tolist()
    data.iloc[a,2] = i
    i += 1
    j += 10

In [200]:
#BMI 카테고리
i=0
index =[]
while i <5 :
    if i == 0:
        a = data.loc[data.BMI<18.5].index.tolist()
        data.iloc[a,3] = i
        for j in a:
            index.append(j)
        i += 1
    elif i == 1:
        b = data.loc[data.BMI<25].index.tolist()
        for j in index:
            b.remove(j)
        data.iloc[b,3] = i
        for k in b:
            index.append(k)
        i +=1
    elif i == 2:
        c = data.loc[data.BMI<30].index.tolist()
        for j in index:
            c.remove(j)
        data.iloc[c,3] = i
        for k in c :
            index.append(k)
        i += 1
    elif i == 3 :
        d = data.loc[data.BMI<40].index.tolist()
        for j in index:
            d.remove(j)
        data.iloc[d,3] =i
        for k in d:
            index.append(k)
        i +=1
    elif i == 4 :
        e = data.loc[data.BMI<50].index.tolist()
        for j in index:
            e.remove(j)
        data.iloc[e,3]=i
        i+=1

0
31
1
2
3
4

In [ ]:
# 날짜 변환

for i, row in data.iterrows():
    a = row["OperationDate"].split("/")
    print(a)
    if len(a) == 3:
        print(a)
        data.ix[i,"OperationDate"] = "20"+str(a[2])+"."+str(a[0])+"."+str(a[1])

In [72]:
clinic=pd.read_csv("./clinic.csv")